love_defending/hyllt/app/models.py
# -*- coding: utf-8 -*-
"""
Created on 2017/05/17 12:36:23

@author: mac
"""

from flask_login import UserMixin, AnonymousUserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from . import db, login_manager


class Permission(object):
    VIEW_MKT = 0x01
    VIEW_ALL = 0x02
    ADMIN = 0x07


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.INTEGER, primary_key=True)
    name = db.Column(db.VARCHAR(16), nullable=False)
    password_hash = db.Column(db.String(128), nullable=False)
    role_id = db.Column(db.INTEGER, db.ForeignKey('roles.id'), default=Permission.VIEW_ALL, nullable=False)

    @property
    def password(self):
        raise ValueError('can\'t get password.')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def can(self, permission):
        return self.role is not None and (self.role.permission & permission) == permission

    def is_admin(self):
        return self.can(Permission.ADMIN)

    def __repr__(self):
        return r'<User {0}>'.format(self.name)


class AnonymousUser(AnonymousUserMixin):
    def can(self, permission):
        return False

    def is_admin(self):
        return False


login_manager.anonymous_user = AnonymousUser


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.INTEGER, primary_key=True)
    name = db.Column(db.VARCHAR(16))
    permission = db.Column(db.INTEGER, default=Permission.VIEW_ALL)
    users = db.relationship('User', backref='role', lazy='dynamic')

    def __unicode__(self):
        return r'<Role {name}>'.format(name=self.name)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

love_defending/hyllt/app/__init__.py
# -*- coding: utf-8 -*-
"""
create on 2018-01-07 下午7:38

author @heyao
"""

from flask import Flask

from flask_admin import Admin
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_pymongo import PyMongo
from flask_sqlalchemy import SQLAlchemy

from config import config

admin = Admin(template_mode='bootstrap3')
bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
mongodb = PyMongo()

login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
login_manager.login_message = '请先登录。'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    admin.init_app(app)
    bootstrap.init_app(app)
    mongodb.init_app(app, config_prefix='MONGO')
    db.init_app(app)
    login_manager.init_app(app)

    from .main import main as main_blueprint
    from .auth import auth as auth_blueprint
    from .user import user as user_blueprint

    app.register_blueprint(main_blueprint)
    app.register_blueprint(auth_blueprint, url_prefix='/auth')
    app.register_blueprint(user_blueprint, url_prefix='/user')

    return app

love_defending/hyllt/app/main/__init__.py
# -*- coding: utf-8 -*-
"""
create on 2018-01-07 下午7:48

author @heyao
"""

from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

love_defending/hyllt/app/main/views.py
# -*- coding: utf-8 -*-
"""
create on 2018-01-07 下午7:48

author @heyao
"""

import sys

import math
from flask import render_template, flash, redirect, url_for, request
from flask_login import login_required

from . import main
from .. import mongodb

reload(sys)
sys.setdefaultencoding('utf-8')


class Pagination(object):
    def add_arg(self, name, value):
        setattr(self, name, value)


def num2str(num):
    if num < 10000:
        return num
    if num < 100000000:
        return str(round(num * 1. / 10000, 2)) + '万'
    else:
        return str(round(num * 1. / 100000000, 2)) + '亿'


def generate_video_list(videos, page, pagesize=20):
    total_items = videos.count()
    videos_info = videos.skip((page - 1) * pagesize).limit(pagesize)
    videos = []
    for video in videos_info:
        video['total_views'] = num2str(video['total_views'])
        video['full_title'] = video['title']
        video['title'] = video['title'][:14] + '…' if len(video['title']) > 14 else '{0:　<14}'.format(video['title'])
        video['collect'] = video['collect'] if 'collect' in video else 0
        videos.append(video)
    pages = int(math.ceil(total_items * 1. / pagesize))

    def get_info():
        max_page = pages + 1
        for i in range(max(1, page - 4), min(max_page, max(1, page - 4) + 10)):
            yield i

    pagination = Pagination()
    pagination.add_arg('has_prev', page != 1)
    pagination.add_arg('page', page)
    pagination.add_arg('iter_pages', get_info)
    pagination.add_arg('has_next', (total_items / pagesize) > page)
    pagination.add_arg('pages', pages)
    return pagination, videos


@main.route('/video/<type>/<page>')
@login_required
def videos(type='total', page=1):
    page = int(page)
    pagesize = 20
    sort_key = dict(
        total='total_views',
        day='views_per_day',
        date='date'
    )[type]
    videos = mongodb.db['video_list'].find().sort([('read_status', 1), (sort_key, -1)])
    pagination, videos = generate_video_list(videos, page, pagesize)
    return render_template('love_defending.html', videos=videos, pagination=pagination, page=page, type=type)


@main.route('/video/mark/<video_id>/<page>/<status>')
@login_required
def video_mark(video_id, page, status=1):
    status = int(status)
    if status != 0 and status != 1:
        flash("失败")
    if status == 1:
        mongodb.db['video_list'].update(
            {'_id': video_id},
            {'$set': {'read_status': status}}
        )
    else:
        mongodb.db['video_list'].update(
            {'_id': video_id},
            {'$unset': {'read_status': 1}}
        )
    return redirect(url_for('main.videos', page=page, type='total'))


@main.route('/video/collect/<video_id>/<page>/<status>')
@login_required
def video_collect(video_id, page, status=1):
    status = int(status)
    if status != 0 and status != 1:
        flash("失败")
    mongodb.db['video_list'].update(
        {'_id': video_id},
        {'$set': {'collect': status}}
    )
    return redirect(url_for('main.videos', page=page, type='total'))


@main.route('/')
@login_required
def index():
    return render_template('index.html')


@main.route('/video/<type>/<keyword>/<page>')
@login_required
def search_video(type='total', keyword='', page=1):
    page = int(page)
    pagesize = 20
    sort_key = dict(
        total='total_views',
        day='views_per_day',
        date='date'
    )[type]
    videos = mongodb.db['video_list'].find({'title': {'$regex': keyword}}).sort([('read_status', 1), (sort_key, -1)])
    pagination, videos = generate_video_list(videos, page, pagesize)
    return render_template('love_defending.html', videos=videos, pagination=pagination, page=page, type=type)

love_defending/hyllt/app/user/__init__.py
# -*- coding: utf-8 -*-
"""
create on 2018-01-20 下午8:14

author @heyao
"""

from flask import Blueprint

user = Blueprint('user', __name__)

from . import views

love_defending/hyllt/app/user/views.py
# -*- coding: utf-8 -*-
"""
create on 2018-01-20 下午8:19

author @heyao
"""
from flask import render_template
from flask_login import login_required

from app import mongodb
from app.main.views import generate_video_list
from . import user


@user.route('/video/<type>/<page>')
@login_required
def videos(type='total', page=1):
    page = int(page)
    pagesize = 20
    sort_key = dict(
        total='total_views',
        day='views_per_day',
        date='date'
    )[type]
    videos = mongodb.db['video_list'].find({'collect': 1}).sort([('read_status', 1), (sort_key, -1)])
    pagination, videos = generate_video_list(videos, page, pagesize)
    return render_template('user/info.html', videos=videos, pagination=pagination, page=page, type=type)

love_defending/hyllt/app/templates/_macro.html
{% macro pagination_widget(pagination, endpoint) %}
    <ul class="pagination">
        {% if pagination.pages > 1 %}
            <li{% if not pagination.has_prev %} class="disabled"{% endif %}><a href="{% if pagination.has_prev %}{{ url_for(endpoint,
page = pagination.page - 1, **kwargs) }}{% else %}#{% endif %}">
                &laquo; </a>
            </li>
            {% for p in pagination.iter_pages() %}
                {% if p %}
                    {% if p == pagination.page %}
                        <li class="active">
                            <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
                        </li>
                    {% endif %} {% else %}
                    <li class="disabled"><a href="#">&hellip;</a></li>
                {% endif %}
            {% endfor %}
            <li{% if not pagination.has_next %} class="disabled"{% endif %}><a href="{% if pagination.has_next %}{{ url_for(endpoint,
page = pagination.page + 1, **kwargs) }}{% else %}#{% endif %}">
                &raquo; </a>
            </li>
        {% endif %}
    </ul>
{% endmacro %}

love_defending/hyllt/app/templates/base.html
<!DOCTYPE html>
{% extends "bootstrap/base.html" %}
{% import 'admin/layout.html' as layout with context %}

{% block title %}
{% endblock %}

{% block navbar %}
    <script type="text/javascript" src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.bootcss.com/echarts/3.8.5/echarts.js"></script>
    <div class="container">
        <nav class="navbar navbar-default" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">一起看片</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="{{ url_for('main.videos', page=1, type='total') }}">爱情保卫战</a></li>
                    {% if current_user.name == "llt" %}
                        <li><a class="navbar-brand" href="{{ url_for('user.videos', type='total', page=1) }}">小乖乖终于睡得香香的了，爱❤️你</a></li>
                    {% endif %}
                </ul>
                {% include 'login_info.html' %}
            </div>
        </nav>
    </div>
{% endblock %}

{% block content %}
    <div class="container">
        {% block messages %}
            {{ layout.messages() }}
        {% endblock %}
        {% block page_content %}{% endblock %}
    </div>
    <style>
        body {
            -webkit-font-smoothing: antialiased;
        }
    </style>
{% endblock %}

love_defending/hyllt/app/templates/index.html
{% extends "base.html" %}
{% import "_macro.html" as macro %}

{% block title %}
    一起看片
{% endblock %}

{% block page_content %}
    <div class="container">
    <div class="row clearfix">
        <div class="bd">
            <div class="col-md-12 column">
                <div class="row clearfix">
                    <div class="col-md-2 column">
                        <a href="{{ url_for('main.videos', page=1, type='total') }}" style="text-decoration: none;">
                            <img class="folder" src="http://puui.qpic.cn/vcolumn_vt_pic/0/m2yiyo1515246375/0"
                                 width="165"
                                 height="231"/>
                        </a>
                    </div>
                    <div class="col-md-3 column" style="margin-left: -30px;">
                        <div class="row clearfix">
                            <div class="col-md-12 column" style="margin-top: 0px;">
                                <h4><a href="{{ url_for('main.videos', page=1, type='total') }}"
                                       style="text-decoration: none;">爱情保卫战</a></h4>
                            </div>
                            <div class="row clearfix">
                                <div class="col-md-12 column" style="margin-top: 5px;">
                                    主持人： 赵川
                                </div>
                            </div>
                            <div class="row clearfix">
                                <div class="col-md-12 column" style="margin-top: 5px;">
                                    地　区: 内地
                                </div>
                            </div>
                            <div class="row clearfix">
                                <div class="col-md-12 column" style="margin-top: 5px;">
                                    电视台: 天津卫视
                                </div>
                            </div>
                            <div class="row clearfix">
                                <div class="col-md-12 column" style="margin-top: 5px;">
                                    语　言: 普通话
                                </div>
                            </div>
                            <div class="row clearfix">
                                <div class="col-md-12 column" style="margin-top: 5px;">
                                    首播时间: 2011-06-18
                                </div>
                            </div>
                            <div class="row clearfix">
                                <div class="col-md-12 column" style="margin-top: 5px;">
                                    简　介： 天津卫视新推出的“后婚恋时代”情感综艺新版块节目。
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style>
        .row {
            margin-top: 2px;
            margin-left: 0px;
        }

        .folder {
            box-shadow: 0 1px 6px rgba(0, 0, 0, .35);
        }
    </style>
{% endblock %}

love_defending/hyllt/app/templates/login_info.html
<ul class="nav navbar-nav navbar-right">
    {% if current_user.is_authenticated %}
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
               aria-haspopup="true"
               aria-expanded="false">{{ current_user.name }}<span class="caret"></span></a>
            <ul class="dropdown-menu">
                {% if current_user.is_admin() %}
                    <li><a href="{{ url_for('admin.index') }}">管理</a></li>
                {% endif %}
                <li><a href="{{ url_for('user.videos', type='total', page=1) }}">收藏列表</a></li>
                <li><a href="{{ url_for('auth.modify') }}">修改密码</a></li>
                <li><a href="{{ url_for('auth.logout') }}">退出</a></li>
            </ul>
        </li>
    {% else %}
        <li><a href="{{ url_for('auth.login') }}">登录</a></li>
    {% endif %}
</ul>

love_defending/hyllt/app/templates/love_defending.html
{% extends "base.html" %}
{% import "_macro.html" as macro %}

{% block title %}
    爱情保卫战
{% endblock %}

{% block page_content %}
    <div class="container">
        <div class="row clearfix">
            <div class="col-md-12 column">
                {% include "search_bar.html" %}
            </div>
            <HR align=center width=1100 color=#987cb9 SIZE=1>
            <div class="col-md-12 column">
                <div class="row clearfix">
                    {% for video in videos %}
                        <div class="col-md-3 column">
                            <div class="row clearfix">
                                <div class="col-md-6 column">
                                    <a href="{{ video.url }}" title="{{ video.full_title }}" target="_blank"
                                       style="text-decoration: none;">
                                        <img src="{{ video.img_url }}" width="124" height="70"/>
                                        <div class="images-content">
                                            &nbsp;<span style="font-size: 8px;">{{ video.date_str }}&nbsp;|&nbsp;{{ video.duration }}</span>
                                        </div>
                                    </a>
                                </div>
                                <div class="col-md-6 column" style="margin-left: -15px;">
                                    <div class="row clearfix">
                                        <div class="col-md-12 column">
                                            <a href="{{ video.url }}" title="{{ video.full_title }}" target="_blank"
                                               style="text-decoration: none;">
                                                <strong>{{ video.title }}</strong>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="row clearfix">
                                        <div class="col-md-8 column" style="margin-top: 5px;">
                                            {{ video.total_views }}
                                        </div>
                                        <div class="col-md-4 column" style="margin-top: 5px;">
                                            <a href="{% if video.read_status == 1 %}
{{ url_for('main.video_mark', video_id=video.id, page=page, status=0) }}
{% else %}
{{ url_for('main.video_mark', video_id=video.id, page=page, status=1) }}
{% endif %}
"
                                               type="button" class="btn btn-{% if video.read_status == 1 %}default{% else %}primary{% endif %} btn-xs">标记</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% if loop.index % 4 == 0 %}
                            <HR align=center width=1100 color=#987cb9 SIZE=1>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <style>
        .images-content {
            margin-left: 15px;
            position: absolute;
            z-index: 1;
            left: 0;
            bottom: 0;
            width: 85%;
            color: #fff;
            background: rgba(0, 0, 0, .7);
            height: 20px;
            line-height: 20px;
            overflow: hidden;
        }
    </style>
    {% if pagination %}
        <div class="pagination pull-right" style="margin-right: 98px;">
            {{ macro.pagination_widget(pagination, 'main.videos', type=type) }}
        </div>
    {% endif %}
{% endblock %}

love_defending/hyllt/app/templates/search_bar.html
<div class="input" style="width: 80%; margin: 0 auto; ">
    <div class="input-group input-group-lg" style="margin-top: 30px; margin-bottom: 50px;">
        <div class="input-group-btn">
            <button type="button" id="search-type" class="btn btn-default dropdown-toggle"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="width: 120px">
                总点击&nbsp;&nbsp;<span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <li><a href="javascript:void(0);" id="total">总点击</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="javascript:void(0);" id="day">日均点击</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="javascript:void(0);" id="date">更新时间</a></li>
            </ul>
        </div>

        <input type="text" id="search-text" class="form-control">
        <span class="input-group-btn">
            <button id="hm-search" class="btn btn-primary" type="button" style="width: 120px">搜索</button>
        </span>
    </div>
</div>
<script>
    var select_id = "{{ type }}";
    if(select_id === 'total'){
        $("#search-type").html('总点击&nbsp;&nbsp;<span class=\"caret\"></span>');
    }
    else if(select_id=== 'day'){
        $("#search-type").html('日均点击&nbsp;&nbsp;<span class=\"caret\"></span>');
    }
    else if(select_id === 'date'){
        $("#search-type").html('更新时间&nbsp;&nbsp;<span class=\"caret\"></span>');
    }
    function search_text(type, text) {
        if (text === "") {
            if (type === 'total') {
                window.location.href = '{{ url_for('main.videos', page=1, type='total') }}'
            }

            else if (type === 'day') {
                window.location.href = '{{ url_for('main.videos', page=1, type='day') }}'
            }
            else {
                window.location.href = '{{ url_for('main.videos', page=1, type='date') }}'
            }

        }
        else {
            if (type === 'total') {
                var url = '{{ url_for('main.search_video', page=1, keyword="", type='total') }}';
            }
            else if (type === 'day') {
                var url = '{{ url_for('main.search_video', page=1, keyword="", type='day') }}';
            }
            else {
                var url = '{{ url_for('main.search_video', page=1, keyword="", type='date') }}';
            }
            window.location.href = url.replace('//', '/' + text + '/');
        }
    }

    $("#hm-search").click(
        function () {
            var text = $("#search-text").val();
            search_text(select_id, text);
        }
    );

    $(".dropdown-menu a").click(
        function () {
            select_id = $(this).attr("id");
            $("#search-type").html($(this).html() + '&nbsp;&nbsp;<span class=\"caret\"></span>');
        }
    );

    $("body").keydown(function () {
        if (event.keyCode == "13") {
            $('#hm-search').click();
        }
    });

</script>

love_defending/hyllt/app/templates/user/info.html
{% extends "base.html" %}
{% import "_macro.html" as macro %}

{% block title %}
    个人中心
{% endblock %}

{% block page_content %}
    <div class="col-md-12 columns">
        <div class="row clearfix">
            <div class="col-md-12 column">
                <div class="row clearfix">
                    {% for video in videos %}
                        <div class="col-md-3 column">
                            <div class="row clearfix">
                                <div class="col-md-6 column">
                                    <a href="{{ video.url }}" title="{{ video.full_title }}" target="_blank"
                                       style="text-decoration: none;">
                                        <img src="{{ video.img_url }}" width="124" height="70"/>
                                        <div class="images-content">
                                            &nbsp;<span style="font-size: 8px;">
                                                {{ video.date_str }}|{{ video.duration }}
                                            </span>
                                        </div>
                                    </a>
                                </div>
                                <div class="col-md-6 column" style="margin-left: -15px;">
                                    <div class="row clearfix">
                                        <div class="col-md-12 column">
                                            <a href="{{ video.url }}" title="{{ video.full_title }}" target="_blank"
                                               style="text-decoration: none;">
                                                <strong>{{ video.title }}</strong>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="row clearfix">
                                        <div class="col-md-9 column" style="margin-top: 5px;">
                                            {{ video.total_views }}
                                        </div>
                                        <div class="col-md-3 column" style="margin-top: -15px;">
                                            <a type="button"
                                               class="btn btn-{% if video.collect == 0 %}default{% else %}warning{% endif %} btn-xs"
                                               href="{% if video.collect == 1 %}
{{ url_for('main.video_collect', video_id=video.id, page=page, status=0) }}
{% else %}
{{ url_for('main.video_collect', video_id=video.id, page=page, status=1) }}
{% endif %}
">
                                                {% if video.collect == 0 %}未藏{% else %}已藏{% endif %}
                                            </a>
                                            <a href="{% if video.read_status == 1 %}
{{ url_for('main.video_mark', video_id=video.id, page=page, status=0) }}
{% else %}
{{ url_for('main.video_mark', video_id=video.id, page=page, status=1) }}
{% endif %}
"
                                               type="button"
                                               class="btn btn-{% if video.read_status == 1 %}default{% else %}primary{% endif %} btn-xs">标记</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% if loop.index % 4 == 0 %}
                            <HR align=center width=1100 color=#987cb9 SIZE=1>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <style>
        .images-content {
            margin-left: 15px;
            position: absolute;
            z-index: 1;
            left: 0;
            bottom: 0;
            width: 85%;
            color: #fff;
            background: rgba(0, 0, 0, .7);
            height: 20px;
            line-height: 20px;
            overflow: hidden;
        }
    </style>
    {% if pagination %}
        <div class="pagination pull-right" style="margin-right: 98px;">
            {{ macro.pagination_widget(pagination, 'main.videos', type=type) }}
        </div>
    {% endif %}
{% endblock %}